[package]
name = "lsystem"
version = "0.0.1"
authors = [ "Magnus Bjerke Vik <mbvett@gmail.com>" ]

[dependencies]
kiss3d = "0.7.*"
glfw = "0.8.*"
nalgebra = "0.9.*"
ncollide_transformation = "0.5.*"
time = "0.1.*"
num-traits = "0.1.*"
rand = "0.3.*"
strsim = "0.5.*"
lsys = { path = "lsys" }
