lsystem = axiom productions
axiom = string
productions = 1*3production
production = predicate successor
predicate = variable
successor = string
string = 1*3(symbol / stack)
stack = "[" string "]"
symbol = variable / operation
variable = "F" / "X"
operation = "+" / "-" / "^" / "&" / ">" / "<"
