iterations: 7
angle: 0.3927
step: 0.2
width: 0.1
shrink_rate: 1.5
colors:
  -
    - 0.7568627595901489
    - 0.6039215922355652
    - 0.41960784792900085
  -
    - 0.30000001192092896
    - 1
    - 0.20000000298023224
command_map:
  "!": Shrink
  "#": Width
  "&": PitchDown
  "'": NextColor
  "+": YawLeft
  "-": YawRight
  "<": RollLeft
  ">": RollRight
  "F": Forward
  "f": Forward
  "[": Push
  "]": Pop
  "^": PitchUp
  "{": BeginSurface
  "|": UTurn
  "}": EndSurface
