lsystem = axiom productions
axiom = string
productions = 1*2production
production = predecessor successor
predecessor = variable
successor = string
string = 1*6(symbol / stack)
stack = "[" string "]"
symbol = variable / operation
variable = "F" / "X"
operation = "+" / "-" / "^" / "&" / ">" / "<"
